### ISSUE TITLE
Downloading photos uploaded after certain date (Feature request)

### ISSUE THREAD

**Issue by paramjitrohit** [althonos/InstaLooter#12]
### (Feature request)
Hi althonos, thanks for this useful project. Can we implement a feature which helps us to download images uploaded in a certain timeframe, like in the last week or so, or after a certain date (between dates, etc...)? This can be useful if one is following a popular username, or if one wants to sync local folders with online albums.

**Comment by althonos** [comment]
Hi ! I'll check that, shouldn't be too hard to implement since the filtering of images is done prior to download, so I could add a datetime check.

**Comment by disrupted** [comment]
that would be a great addition @althonos

**Comment by althonos** [comment]
Done ! Just give it a try and reopen issue if it doesn't work properly :)

**Comment by paramjitrohit** [comment]
I am getting the error:
`Traceback (most recent call last):
  File "/usr/bin/instaLooter", line 11, in <module>
    load_entry_point('instaLooter==0.3.1', 'console_scripts', 'instaLooter')()
  File "/usr/lib/python3.5/site-packages/instaLooter/__main__.py", line 69, in main
    timeframe = get_times_from_cli(args['--time'])
  File "/usr/lib/python3.5/site-packages/instaLooter/utils.py", line 23, in get_times_from_cli
    today = datetime.today.today()
AttributeError: module 'datetime' has no attribute 'today'`

**Comment by disrupted** [comment]
doesn't work for me either

**Comment by althonos** [comment]
Even with latest push ?
Try with a plain date, e.g. 2016-12-05:2016-10-05 and tell me if it work if
you please :)

**Comment by disrupted** [comment]
even then :/

`Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "instaLooter/__main__.py", line 45, in <module>
    from . import __version__, __author__, __author_email__
SystemError: Parent module '' not loaded, cannot perform relative import`

**Comment by althonos** [comment]
Grrr. I'm working on it right now.

**Comment by althonos** [comment]
Did you pull the latest changes from the repository ? 
It worked just fine with me, doing the following (worked in both Py3.5 and Py2.7):
```bash
git clone https://github.com/althonos/InstaLooter
cd InstaLooter
python3 -m instaLooter mysteryjets /tmp -t thisweek
```

**Comment by paramjitrohit** [comment]
Hi @althonos . The commands you posted work just fine. I think I was using the (old?) PyPI installation. (Did you push the changes to PyPI just yet?) I git cloned the repository and pip installed it, thinking it installed the new version. But it wasn't so. Thanks a lot for the fix! (As a side comment, do you mind referring me to some resources to learn python scripting in detail so that I can contribute rather than bothering good souls such as yourself :) ).

**Comment by althonos** [comment]
I wanted to make sure everything worked before pushing to PyPI :)

When you `pip install` something, you have to pass it the `--upgrade` flag or else if `pip` detects that something is already installed, it won't upgrade :)

As for Python resources, I learned a lot through my University courses (in French) so that won't interest you, but I also used a book called Learning Python by Mark Lutz.

In general all the O'Reilly book about Python are really good and you may find them online somewhere :)

**Comment by disrupted** [comment]
@althonos it is working! don't know what caused the errors before but it's perfect now. thanks for your work!

**Comment by disrupted** [comment]
one more thing: do I have to specifiy a timeframe for every call now?

This is what I end up with if I don't set the `-t` option:

`Traceback (most recent call last):
  File "/usr/local/bin/instaLooter", line 11, in <module>
    load_entry_point('instaLooter==0.3.1', 'console_scripts', 'instaLooter')()
  File "/usr/local/lib/python3.4/dist-packages/instaLooter/__main__.py", line 79, in main
    with_pbar=not args['--quiet'], timeframe=timeframe,
  File "/usr/local/lib/python3.4/dist-packages/instaLooter/core.py", line 337, in download
    condition=condition, timeframe=timeframe)
  File "/usr/local/lib/python3.4/dist-packages/instaLooter/core.py", line 371, in _fill_media_queue
    for media in self.medias(media_count=media_count, with_pbar=with_pbar, timeframe=timeframe):
  File "/usr/local/lib/python3.4/dist-packages/instaLooter/core.py", line 245, in _timeless_medias
    for page in self.pages(media_count=media_count, with_pbar=with_pbar):
  File "/usr/local/lib/python3.4/dist-packages/instaLooter/core.py", line 211, in pages
    self.metadata = self._parse_metadata_from_profile_page(data)
  File "/usr/local/lib/python3.4/dist-packages/instaLooter/core.py", line 410, in _parse_metadata_from_profile_page
    user = data["entry_data"][self._page_name][0]["user"]
KeyError: 'ProfilePage'`

**Comment by althonos** [comment]
Yes, though this seem to be a problem with requests, the http library I used. Open a separate issue if this happens too much :)
